### PR TITLE
JSON interface for stories

### PR DESCRIPTION
**Pull request by Skyshayde**
I needed a way to get the story data for my epub code and by the time I realized I could just access it directly I was already halfway through.  I guess it could still be useful for plugins or something.  Idk

### CODE REVIEW

**Comment by raymestalez** [comment]
Thanks! Though in the future I will most likely replace it with REST API.

Btw, what do you mean by "access it directly"? Like by parsing html?

**Comment by Skyshayde** [comment]
No, I was planning on accessing the db.

**Comment by raymestalez** [comment]
Oh, got it. Well, it probably would be best to access it through api.
Also, since people requested it, I am planning to include the "download pdf/epub" feature in the future.

**Comment by Skyshayde** [comment]
Yeah, that's what I was working on.  An ebook download button.

**Comment by raymestalez** [comment]
That's really cool =)

**Comment by raymestalez** [comment]
Now  that I think about it in this case of course it makes sense to access db directly. I just thought you were making a standalonre script at first.

**Comment by Skyshayde** [comment]
Ah.  Have you thought about whether or not we should store the files or not?  Preliminary tests have it running quick enough that it probably isn't necessary but mass cloud storage isn't particularly expensive.  Google cloud storage is a couple cents per GB a month.

**Comment by raymestalez** [comment]
I think it's best to start with the simplest version at first, the one that requires the least code and is easiest to implement, which is probably generating it on request, and then move on to storing files when necessary. Though if the amount of complexity/effort is similar either way, then it's best to store files.

**Pull request merged**
